version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "font-awesome-sass"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
