port: 3000
paginate: 7
markdown: kramdown
exclude:
  - Gemfile*
  - Rakefile
timezone: Europe/Rome
plugins:
  - jekyll-gist
  - jekyll-paginate
sass:
  load_paths:
    - _sass
    - vendor/bundle/ruby/3.1.0/gems
  sourcemap: never

site_address: http://baldowl.github.io
title: Baldowl - my nest somewhere in GitHub's forest

disqus_shortname: baldowl
