port: 3000
paginate: 7
markdown: kramdown
exclude:
  - config.rb
  - icons
  - Rakefile
  - sass
timezone: Europe/Rome

site_address: http://baldowl.github.io
title: Baldowl - my nest somewhere in GitHub's forest

disqus_shortname: baldowl
