port: 3000
paginate: 7
markdown: kramdown
exclude:
  - Gemfile*
  - Rakefile
  - config.rb
  - images/icons/
  - stylesheets/sass/
timezone: Europe/Rome
plugins:
  - jekyll-gist
  - jekyll-paginate

site_address: http://baldowl.github.io
title: Baldowl - my nest somewhere in GitHub's forest

disqus_shortname: baldowl
