auto: true
server: true
server_port: 3000
paginate: 6
markdown: kramdown
exclude:
  - config.rb
  - Rakefile
  - sass

base_url: http://baldowl.github.com
title: Baldowl - my nest somewhere in GitHub's forest

disqus_shortname: baldowl
