port: 3000
paginate: 7
markdown: kramdown
exclude:
  - config.rb
  - icons
  - Rakefile
  - sass
timezone: Europe/Rome
gems:
  - jekyll-gist
  - jekyll-paginate

site_address: http://baldowl.github.io
title: Baldowl - my nest somewhere in GitHub's forest

disqus_shortname: baldowl
